### ISSUE TITLE
您好，有关倒着安装雷达的问题。

### ISSUE THREAD

**Issue by lianhuanhuaa** [nkymzsy/LIO-SAM-MID360#11]
我编译成功之后，在rviz界面发现正着放置雷达，生成的点云地图还比较稳定，但是倒着放置雷达之后，在rviz界面出现了雷达的位置乱跳，不知道该怎么解决这个问题，具体是哪个模块的问题？希望可以解答，十分感谢！

**Comment by nkymzsy** [comment]
倒置要调节IMU外参矩阵

**Comment by lianhuanhuaa** [comment]
您好，十分感谢您的回复，我将IMU的外参改了一下，但是倒着放置时生成的点云地图中雷达的位置还是乱跳，也可能是我修改的文件或者参数不对，请问是修改paramsLivoxIMU.yaml里的extrinsicRot、extrinsicRPY参数吗，另外需不需要修改程序里的相关算法，期待您的回复，十分感谢！

**Comment by Yangchengshuai** [comment]
> extrinsicRPY

extrinsicRPY是什么意思？如果imu坐标系与默认坐标系（y前，x右，z上 ）不同，需要做哪些修改？

**Comment by Yangchengshuai** [comment]
> 您好，十分感谢您的回复，我将IMU的外参改了一下，但是倒着放置时生成的点云地图中雷达的位置还是乱跳，也可能是我修改的文件或者参数不对，请问是修改paramsLivoxIMU.yaml里的extrinsicRot、extrinsicRPY参数吗，另外需不需要修改程序里的相关算法，期待您的回复，十分感谢！

我的也是Z字形跳动

**Comment by Yangchengshuai** [comment]
> extrinsicRPY

你好

> 您好，十分感谢您的回复，我将IMU的外参改了一下，但是倒着放置时生成的点云地图中雷达的位置还是乱跳，也可能是我修改的文件或者参数不对，请问是修改paramsLivoxIMU.yaml里的extrinsicRot、extrinsicRPY参数吗，另外需不需要修改程序里的相关算法，期待您的回复，十分感谢！

你好，想问下解决了吗

**Comment by lianhuanhuaa** [comment]
你好，修改了外参但是问题没有解决，也可能是我修改的地方不对，后期就没继续用这个代码了

**Comment by PixelVoyager-30** [comment]
> 倒置要调节IMU外参矩阵

疑问，MID-360 lidar和imu坐标系相同，倒置安装后坐标系不还是一样么，为什么需要修改外参呢

**Comment by lucianzhong** [comment]
倒转 mid360 建图， 这个问题yaml文件需要怎么修改？

**Comment by sssecs** [comment]
你们好，我也遇到了这个问题，将imuPreintegration.cpp第214行的`boost::shared_ptr<gtsam::PreintegrationParams> p = gtsam::PreintegrationParams::MakeSharedU(imuGravity);` 改为 `boost::shared_ptr<gtsam::PreintegrationParams> p = gtsam::PreintegrationParams::MakeSharedU(-imuGravity);` 即可
