### ISSUE TITLE
您好，mid360上市了吗，我在livox的官网也没找到售卖途径？

### ISSUE THREAD

**Issue by Bourne98** [nkymzsy/LIO-SAM-MID360#2]

**Comment by nkymzsy** [comment]
应该还没有

**Comment by Bourne98** [comment]
> 应该还没有

冒昧问一下您的获取途径，或者说您是合作高校？

**Comment by nkymzsy** [comment]
> > 应该还没有
> 
> 冒昧问一下您的获取途径，或者说您是合作高校？

是的 目前的只是测试样机

**Comment by Bourne98** [comment]
> > > 应该还没有
> > 
> > 
> > 冒昧问一下您的获取途径，或者说您是合作高校？
> 
> 是的 目前的只是测试样机

好的，谢谢您
