### ISSUE TITLE
mid360的IMU数据相关问题

### ISSUE THREAD

**Issue by Dangko** [nkymzsy/LIO-SAM-MID360#9]
你好，我在使用 mid360 时，发现 mid360 的 IMU 数据似乎与平常的 IMU 数据不太一样，例如下面这张图一样，ouster 内置的 IMU 数据在 z 轴上明显有重力加速度，但是 mid360 的 IMU 数据却仅有不到 1，请问你遇到过这种情况吗？ mid360 的 IMU 数据应该怎样处理呢(特别是如何去除重力，量纲上感觉明显有差距)？
![mid360_IMU数据](https://github.com/nkymzsy/LIO-SAM-MID360/assets/48203571/cccd49ea-6f76-4ec6-adc0-9a12016887d1)

**Comment by nkymzsy** [comment]
官方手册写了IMU给出的重力加速度大小单位为g 自己换算成m/s^2就行
参阅https://livox-wiki-cn.readthedocs.io/zh-cn/latest/tutorials/new_product/mid360/livox_eth_protocol_mid360.html#imu
字段 | 偏移(字节) | 数据类型 | 描述
-- | -- | -- | --
gyro_x | 0 | float | Unit: rad/s
gyro_y | 4 | float | Unit: rad/s
gyro_z | 8 | float | Unit: rad/s
acc_x | 12 | float | Unit: g
acc_y | 16 | float | Unit: g
acc_z | 20 | float | Unit: g
